--- #YAML:1.0
name:               Digest-PSHA
version:            0.51
abstract:           Perl implementation of P_SHA-1 and P_SHA256
author:
    - Alexey Semenoff [http://swaj.net]
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC:  1
    Digest::SHA:   1.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
