---
abstract: 'Perl implementation of P_SHA-1 and P_SHA256 digests (pseudorandom functions) described in RFC 4346 and RFC 5246.'
author:
  - 'Alexey Semenoff [http://swaj.net]'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-PSHA
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC: 1
  Digest::SHA: 1.1
version: 0.50
